### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by cz9dev** [garciaguimeras/jnauta#1]
Hola muy bueno tu trabajo, ¿podrías documentar mas tu librería? https://github.com/garciaguimeras/jnauta/tree/master/jnauta-net ademas si utilizo la lib importándola desde jitpack no funciona solo esta compilada para jnauta-mail. En espera, vi tu app MiNauta y de veras que esta buena, quizás pudieras llevar el conocimiento de MiNauta a esta lib. Saludos

**Comment by garciaguimeras** [comment]
Hola Carlos, 

hace tiempo no le doy soporte a esto. De hecho me asombra que aun funcione, que la gente de etecsa no haya cambiado en algo el portal de login.

Por ahi un amigo me pidio hace un tiempo agregar las cuentas nuevas en MLC y no he tenido tiempo de hacerlo. Tambien hay un portal nuevo y el MiNauta sigue redirigiendo al viejo. Tampoco me he dedicado a ver que se puede hacer en ese sentido.

Estoy borrando lo del jitpack porque realmente ya no funciona (en algun momento si lo hizo).

En cuanto al uso como tal, creo q los metodos principales los puedes encontrar aca:
https://github.com/garciaguimeras/jnauta/blob/master/jnauta-net/src/main/java/dev/blackcat/jnauta/net/Authentication.java
En el proyecto de MiNauta podras ver como se usan en la practica.
Tambien hay una version .NET/Desktop que es una especie de rewrite de la misma libreria pero para .NET.

**Comment by cz9dev** [comment]
Me gusto la forma en la que trabaja la app y de por si la librería ya que poseo dominio de portal en el nauta hogar, mas aun por que mi niño le gusta mucho navegar y de esta forma puedo darle el tiempo que deseo diario. me dispuse a trabajar con tu lib ya que el ya se dio cuenta de como abrir nuevamente aunque se cerrara la conexión y me puse a crear una que necesite una pass para entrar como medida de seguridad, mas nada que un activity con una cuenta que escribo en las preferencias compartidas, jj bueno sin mas deja echarle un ojo a lo que me compartiste y de paso tienes idea para crear una nueva version de tu app que aun es utilizada y si quieres y tienes tiempo actualizar tu lib y algo mas. Mis felicitaciones para ti por la iniciativa

**Comment by garciaguimeras** [comment]
Bueno yo solo tocaria la libreria jnauta si hubiera algun cambio en el mecanismo de login/logout del portal, o en la pagina... como ves ahi se parsea el html. Tambien se podria mejorar ese parseo usando una libreria mas pro, como jsoup.

Lo q me dices, q es una especie de control parental, es mejor hacerlo directamente en la app Android (me dijiste q ya lo hiciste un activity), pero no lo pasaria a la libreria pq en si no forma parte de lo pide el portal de etecsa para autenticarse. 

La solucion del control parental se puede generalizar dando la alternativa de activarlo o desactivarlo segun el deseo del usuario, en los settings de la app, y seria una buena mejora. Si quieres contribuir de alguna forma con la app lo puedes hacer, podemos conversar de q forma hacerlo.

Yo hace mas de dos años q no toco nada de Android, tengo el ide super desactualizado y tendria q volver a ponerme al dia para tocar algo ahi jjj.
